colorNames = [
  { hex: 'B0BF1A', name: "Acid green" },
  { hex: '7CB9E8', name: "Aero" },
  { hex: 'C9FFE5', name: "Aero blue" },
  { hex: 'B284BE', name: "African violet" },
  { hex: '5D8AA8', name: "Air Force blue (RAF)" },
  { hex: '00308F', name: "Air Force blue (USAF)" },
  { hex: '72A0C1', name: "Air superiority blue" },
  { hex: 'AF002A', name: "Alabama crimson" },
  { hex: 'F0F8FF', name: "Alice blue" },
  { hex: 'E32636', name: "Alizarin crimson" },
  { hex: 'C46210', name: "Alloy orange" },
  { hex: 'EFDECD', name: "Almond" },
  { hex: 'E52B50', name: "Amaranth" },
  { hex: 'F19CBB', name: "Amaranth pink" },
  { hex: 'AB274F', name: "Amaranth purple" },
  { hex: 'D3212D', name: "Amaranth red" },
  { hex: '3B7A57', name: "Amazon" },
  { hex: 'FFBF00', name: "Amber" },
  { hex: 'FF7E00', name: "Amber (SAE/ECE)" },
  { hex: 'FF033E', name: "American rose" },
  { hex: '9966CC', name: "Amethyst" },
  { hex: 'A4C639', name: "Android green" },
  { hex: 'F2F3F4', name: "Anti-flash white" },
  { hex: 'CD9575', name: "Antique brass" },
  { hex: '665D1E', name: "Antique bronze" },
  { hex: '915C83', name: "Antique fuchsia" },
  { hex: '841B2D', name: "Antique ruby" },
  { hex: 'FAEBD7', name: "Antique white" },
  { hex: '008000', name: "Ao (English)" },
  { hex: '8DB600', name: "Apple green" },
  { hex: 'FBCEB1', name: "Apricot" },
  { hex: '00FFFF', name: "Aqua" },
  { hex: '7FFFD4', name: "Aquamarine" },
  { hex: '4B5320', name: "Army green" },
  { hex: '3B444B', name: "Arsenic" },
  { hex: '8F9779', name: "Artichoke" },
  { hex: 'E9D66B', name: "Arylide yellow" },
  { hex: 'B2BEB5', name: "Ash grey" },
  { hex: '87A96B', name: "Asparagus" },
  { hex: 'FF9966', name: "Atomic tangerine" },
  { hex: 'A52A2A', name: "Auburn" },
  { hex: 'FDEE00', name: "Aureolin" },
  { hex: '6E7F80', name: "AuroMetalSaurus" },
  { hex: '568203', name: "Avocado" },
  { hex: '007FFF', name: "Azure" },
  { hex: 'F0FFFF', name: "Azure (web color)" },
  { hex: 'F0FFFF', name: "Azure mist" },
  { hex: 'DBE9F4', name: "Azureish white" },
  { hex: '89CFF0', name: "Baby blue" },
  { hex: 'A1CAF1', name: "Baby blue eyes" },
  { hex: 'F4C2C2', name: "Baby pink" },
  { hex: 'FEFEFA', name: "Baby powder" },
  { hex: 'FF91AF', name: "Baker-Miller pink" },
  { hex: '21ABCD', name: "Ball blue" },
  { hex: 'FAE7B5', name: "Banana Mania" },
  { hex: 'FFE135', name: "Banana yellow" },
  { hex: '006A4E', name: "Bangladesh green" },
  { hex: 'E0218A', name: "Barbie pink" },
  { hex: '7C0A02', name: "Barn red" },
  { hex: '848482', name: "Battleship grey" },
  { hex: '98777B', name: "Bazaar" },
  { hex: 'BCD4E6', name: "Beau blue" },
  { hex: '9F8170', name: "Beaver" },
  { hex: 'F5F5DC', name: "Beige" },
  { hex: '2E5894', name: "B'dazzled blue" },
  { hex: '9C2542', name: "Big dip o’ruby" },
  { hex: 'FFE4C4', name: "Bisque" },
  { hex: '3D2B1F', name: "Bistre" },
  { hex: '967117', name: "Bistre brown" },
  { hex: 'CAE00D', name: "Bitter lemon" },
  { hex: 'BFFF00', name: "Bitter lime" },
  { hex: 'FE6F5E', name: "Bittersweet" },
  { hex: 'BF4F51', name: "Bittersweet shimmer" },
  { hex: '000000', name: "Black" },
  { hex: '3D0C02', name: "Black bean" },
  { hex: '253529', name: "Black leather jacket" },
  { hex: '3B3C36', name: "Black olive" },
  { hex: 'FFEBCD', name: "Blanched almond" },
  { hex: 'A57164', name: "Blast-off bronze" },
  { hex: '318CE7', name: "Bleu de France" },
  { hex: 'ACE5EE', name: "Blizzard Blue" },
  { hex: 'FAF0BE', name: "Blond" },
  { hex: '0000FF', name: "Blue" },
  { hex: '1F75FE', name: "Blue (Crayola)" },
  { hex: '0093AF', name: "Blue (Munsell)" },
  { hex: '0087BD', name: "Blue (NCS)" },
  { hex: '0018A8', name: "Blue (Pantone)" },
  { hex: '333399', name: "Blue (pigment)" },
  { hex: '0247FE', name: "Blue (RYB)" },
  { hex: 'A2A2D0', name: "Blue Bell" },
  { hex: '6699CC', name: "Blue-gray" },
  { hex: '0D98BA', name: "Blue-green" },
  { hex: '553592', name: "Blue-magenta violet" },
  { hex: '126180', name: "Blue sapphire" },
  { hex: '8A2BE2', name: "Blue-violet" },
  { hex: '5072A7', name: "Blue yonder" },
  { hex: '4F86F7', name: "Blueberry" },
  { hex: '1C1CF0', name: "Bluebonnet" },
  { hex: 'DE5D83', name: "Blush" },
  { hex: '79443B', name: "Bole" },
  { hex: '0095B6', name: "Bondi blue" },
  { hex: 'E3DAC9', name: "Bone" },
  { hex: 'CC0000', name: "Boston University Red" },
  { hex: '006A4E', name: "Bottle green" },
  { hex: '873260', name: "Boysenberry" },
  { hex: '0070FF', name: "Brandeis blue" },
  { hex: 'B5A642', name: "Brass" },
  { hex: 'CB4154', name: "Brick red" },
  { hex: '1DACD6', name: "Bright cerulean" },
  { hex: '66FF00', name: "Bright green" },
  { hex: 'BF94E4', name: "Bright lavender" },
  { hex: 'D891EF', name: "Bright lilac" },
  { hex: 'C32148', name: "Bright maroon" },
  { hex: '1974D2', name: "Bright navy blue" },
  { hex: 'FF007F', name: "Bright pink" },
  { hex: '08E8DE', name: "Bright turquoise" },
  { hex: 'D19FE8', name: "Bright ube" },
  { hex: '3399FF', name: "Brilliant azure" },
  { hex: 'F4BBFF', name: "Brilliant lavender" },
  { hex: 'FF55A3', name: "Brilliant rose" },
  { hex: 'FB607F', name: "Brink pink" },
  { hex: '004225', name: "British racing green" },
  { hex: 'CD7F32', name: "Bronze" },
  { hex: '737000', name: "Bronze Yellow" },
  { hex: '964B00', name: "Brown (traditional)" },
  { hex: 'A52A2A', name: "Brown (web)" },
  { hex: '6B4423', name: "Brown-nose" },
  { hex: 'cc9966', name: "Brown Yellow" },
  { hex: '1B4D3E', name: "Brunswick green" },
  { hex: 'FFC1CC', name: "Bubble gum" },
  { hex: 'E7FEFF', name: "Bubbles" },
  { hex: 'F0DC82', name: "Buff" },
  { hex: '7BB661', name: "Bud green" },
  { hex: '480607', name: "Bulgarian rose" },
  { hex: '800020', name: "Burgundy" },
  { hex: 'DEB887', name: "Burlywood" },
  { hex: 'CC5500', name: "Burnt orange" },
  { hex: 'E97451', name: "Burnt sienna" },
  { hex: '8A3324', name: "Burnt umber" },
  { hex: 'BD33A4', name: "Byzantine" },
  { hex: '702963', name: "Byzantium" },
  { hex: '536872', name: "Cadet" },
  { hex: '5F9EA0', name: "Cadet blue" },
  { hex: '91A3B0', name: "Cadet grey" },
  { hex: '006B3C', name: "Cadmium green" },
  { hex: 'ED872D', name: "Cadmium orange" },
  { hex: 'E30022', name: "Cadmium red" },
  { hex: 'FFF600', name: "Cadmium yellow" },
  { hex: 'A67B5B', name: "Café au lait" },
  { hex: '4B3621', name: "Café noir" },
  { hex: '1E4D2B', name: "Cal Poly green" },
  { hex: 'A3C1AD', name: "Cambridge Blue" },
  { hex: 'C19A6B', name: "Camel" },
  { hex: 'EFBBCC', name: "Cameo pink" },
  { hex: '78866B', name: "Camouflage green" },
  { hex: 'FFEF00', name: "Canary yellow" },
  { hex: 'FF0800', name: "Candy apple red" },
  { hex: 'E4717A', name: "Candy pink" },
  { hex: '00BFFF', name: "Capri" },
  { hex: '592720', name: "Caput mortuum" },
  { hex: 'C41E3A', name: "Cardinal" },
  { hex: '00CC99', name: "Caribbean green" },
  { hex: '960018', name: "Carmine" },
  { hex: 'D70040', name: "Carmine (M&P)" },
  { hex: 'EB4C42', name: "Carmine pink" },
  { hex: 'FF0038', name: "Carmine red" },
  { hex: 'FFA6C9', name: "Carnation pink" },
  { hex: 'B31B1B', name: "Carnelian" },
  { hex: '56A0D3', name: "Carolina blue" },
  { hex: 'ED9121', name: "Carrot orange" },
  { hex: '00563F', name: "Castleton green" },
  { hex: '062A78', name: "Catalina blue" },
  { hex: '703642', name: "Catawba" },
  { hex: 'C95A49', name: "Cedar Chest" },
  { hex: '92A1CF', name: "Ceil" },
  { hex: 'ACE1AF', name: "Celadon" },
  { hex: '007BA7', name: "Celadon blue" },
  { hex: '2F847C', name: "Celadon green" },
  { hex: 'B2FFFF', name: "Celeste" },
  { hex: '4997D0', name: "Celestial blue" },
  { hex: 'DE3163', name: "Cerise" },
  { hex: 'EC3B83', name: "Cerise pink" },
  { hex: '007BA7', name: "Cerulean" },
  { hex: '2A52BE', name: "Cerulean blue" },
  { hex: '6D9BC3', name: "Cerulean frost" },
  { hex: '007AA5', name: "CG Blue" },
  { hex: 'E03C31', name: "CG Red" },
  { hex: 'A0785A', name: "Chamoisee" },
  { hex: 'F7E7CE', name: "Champagne" },
  { hex: '36454F', name: "Charcoal" },
  { hex: '232B2B', name: "Charleston green" },
  { hex: 'E68FAC', name: "Charm pink" },
  { hex: 'DFFF00', name: "Chartreuse (traditional)" },
  { hex: '7FFF00', name: "Chartreuse (web)" },
  { hex: 'DE3163', name: "Cherry" },
  { hex: 'FFB7C5', name: "Cherry blossom pink" },
  { hex: '954535', name: "Chestnut" },
  { hex: 'DE6FA1', name: "China pink" },
  { hex: 'A8516E', name: "China rose" },
  { hex: 'AA381E', name: "Chinese red" },
  { hex: '856088', name: "Chinese violet" },
  { hex: '7B3F00', name: "Chocolate (traditional)" },
  { hex: 'D2691E', name: "Chocolate (web)" },
  { hex: 'FFA700', name: "Chrome yellow" },
  { hex: '98817B', name: "Cinereous" },
  { hex: 'E34234', name: "Cinnabar" },
  { hex: 'D2691E', name: "Cinnamon" },
  { hex: 'E4D00A', name: "Citrine" },
  { hex: '9FA91F', name: "Citron" },
  { hex: '7F1734', name: "Claret" },
  { hex: 'FBCCE7', name: "Classic rose" },
  { hex: '0047AB', name: "Cobalt blue" },
  { hex: 'D2691E', name: "Cocoa brown" },
  { hex: '965A3E', name: "Coconut" },
  { hex: '6F4E37', name: "Coffee" },
  { hex: 'C4D8E2', name: "Columbia blue" },
  { hex: 'F88379', name: "Congo pink" },
  { hex: '000000', name: "Cool black" },
  { hex: '8C92AC', name: "Cool grey" },
  { hex: 'B87333', name: "Copper" },
  { hex: 'DA8A67', name: "Copper (Crayola)" },
  { hex: 'AD6F69', name: "Copper penny" },
  { hex: 'CB6D51', name: "Copper red" },
  { hex: '996666', name: "Copper rose" },
  { hex: 'FF3800', name: "Coquelicot" },
  { hex: 'FF7F50', name: "Coral" },
  { hex: 'F88379', name: "Coral pink" },
  { hex: 'FF4040', name: "Coral red" },
  { hex: '893F45', name: "Cordovan" },
  { hex: 'FBEC5D', name: "Corn" },
  { hex: 'B31B1B', name: "Cornell Red" },
  { hex: '6495ED', name: "Cornflower blue" },
  { hex: 'FFF8DC', name: "Cornsilk" },
  { hex: 'FFF8E7', name: "Cosmic latte" },
  { hex: '81613e', name: "Coyote brown" },
  { hex: 'FFBCD9', name: "Cotton candy" },
  { hex: 'FFFDD0', name: "Cream" },
  { hex: 'DC143C', name: "Crimson" },
  { hex: 'BE0032', name: "Crimson glory" },
  { hex: '990000', name: "Crimson red" },
  { hex: '00FFFF', name: "Cyan" },
  { hex: '4E82b4', name: "Cyan azure" },
  { hex: '4682BF', name: "Cyan-blue azure" },
  { hex: '28589C', name: "Cyan cobalt blue" },
  { hex: '188BC2', name: "Cyan cornflower blue" },
  { hex: '00B7EB', name: "Cyan (process)" },
  { hex: '58427C', name: "Cyber grape" },
  { hex: 'FFD300', name: "Cyber yellow" },
  { hex: 'FFFF31', name: "Daffodil" },
  { hex: 'F0E130', name: "Dandelion" },
  { hex: '00008B', name: "Dark blue" },
  { hex: '666699', name: "Dark blue-gray" },
  { hex: '654321', name: "Dark brown" },
  { hex: '88654E', name: "Dark brown-tangelo" },
  { hex: '5D3954', name: "Dark byzantium" },
  { hex: 'A40000', name: "Dark candy apple red" },
  { hex: '08457E', name: "Dark cerulean" },
  { hex: '986960', name: "Dark chestnut" },
  { hex: 'CD5B45', name: "Dark coral" },
  { hex: '008B8B', name: "Dark cyan" },
  { hex: '536878', name: "Dark electric blue" },
  { hex: 'B8860B', name: "Dark goldenrod" },
  { hex: 'A9A9A9', name: "Dark gray (X11)" },
  { hex: '013220', name: "Dark green" },
  { hex: '006400', name: "Dark green (X11)" },
  { hex: '00416A', name: "Dark imperial blue" },
  { hex: '6E6EF9', name: "Dark imperial blue" },
  { hex: '1A2421', name: "Dark jungle green" },
  { hex: 'BDB76B', name: "Dark khaki" },
  { hex: '483C32', name: "Dark lava" },
  { hex: '734F96', name: "Dark lavender" },
  { hex: '534B4F', name: "Dark liver" },
  { hex: '543D37', name: "Dark liver (horses)" },
  { hex: '8B008B', name: "Dark magenta" },
  { hex: 'A9A9A9', name: "Dark medium gray" },
  { hex: '003366', name: "Dark midnight blue" },
  { hex: '4A5D23', name: "Dark moss green" },
  { hex: '556B2F', name: "Dark olive green" },
  { hex: 'FF8C00', name: "Dark orange" },
  { hex: '9932CC', name: "Dark orchid" },
  { hex: '779ECB', name: "Dark pastel blue" },
  { hex: '03C03C', name: "Dark pastel green" },
  { hex: '966FD6', name: "Dark pastel purple" },
  { hex: 'C23B22', name: "Dark pastel red" },
  { hex: 'E75480', name: "Dark pink" },
  { hex: '003399', name: "Dark powder blue" },
  { hex: '4F3A3C', name: "Dark puce" },
  { hex: '872657', name: "Dark raspberry" },
  { hex: '8B0000', name: "Dark red" },
  { hex: 'E9967A', name: "Dark salmon" },
  { hex: '560319', name: "Dark scarlet" },
  { hex: '8FBC8F', name: "Dark sea green" },
  { hex: '3C1414', name: "Dark sienna" },
  { hex: '8CBED6', name: "Dark sky blue" },
  { hex: '483D8B', name: "Dark slate blue" },
  { hex: '2F4F4F', name: "Dark slate gray" },
  { hex: '177245', name: "Dark spring green" },
  { hex: '918151', name: "Dark tan" },
  { hex: 'FFA812', name: "Dark tangerine" },
  { hex: '483C32', name: "Dark taupe" },
  { hex: 'CC4E5C', name: "Dark terra cotta" },
  { hex: '00CED1', name: "Dark turquoise" },
  { hex: 'D1BEA8', name: "Dark vanilla" },
  { hex: '9400D3', name: "Dark violet" },
  { hex: '9B870C', name: "Dark yellow" },
  { hex: '00703C', name: "Dartmouth green" },
  { hex: '555555', name: "Davy's grey" },
  { hex: 'D70A53', name: "Debian red" },
  { hex: '40826D', name: "Deep aquamarine" },
  { hex: 'A9203E', name: "Deep carmine" },
  { hex: 'EF3038', name: "Deep carmine pink" },
  { hex: 'E9692C', name: "Deep carrot orange" },
  { hex: 'DA3287', name: "Deep cerise" },
  { hex: 'FAD6A5', name: "Deep champagne" },
  { hex: 'B94E48', name: "Deep chestnut" },
  { hex: '704241', name: "Deep coffee" },
  { hex: 'C154C1', name: "Deep fuchsia" },
  { hex: '056608', name: "Deep Green" },
  { hex: '0E7C61', name: "Deep green-cyan turquoise" },
  { hex: '004B49', name: "Deep jungle green" },
  { hex: '333366', name: "Deep koamaru" },
  { hex: 'F5C71A', name: "Deep lemon" },
  { hex: '9955BB', name: "Deep lilac" },
  { hex: 'CC00CC', name: "Deep magenta" },
  { hex: '820000', name: "Deep maroon" },
  { hex: 'D473D4', name: "Deep mauve" },
  { hex: '355E3B', name: "Deep moss green" },
  { hex: 'FFCBA4', name: "Deep peach" },
  { hex: 'FF1493', name: "Deep pink" },
  { hex: 'A95C68', name: "Deep puce" },
  { hex: '850101', name: "Deep Red" },
  { hex: '843F5B', name: "Deep ruby" },
  { hex: 'FF9933', name: "Deep saffron" },
  { hex: '00BFFF', name: "Deep sky blue" },
  { hex: '4A646C', name: "Deep Space Sparkle" },
  { hex: '556B2F', name: "Deep spring bud" },
  { hex: '7E5E60', name: "Deep Taupe" },
  { hex: '66424D', name: "Deep Tuscan red" },
  { hex: '330066', name: "Deep violet" },
  { hex: 'BA8759', name: "Deer" },
  { hex: '1560BD', name: "Denim" },
  { hex: '669999', name: "Desaturated cyan" },
  { hex: 'C19A6B', name: "Desert" },
  { hex: 'EDC9AF', name: "Desert sand" },
  { hex: 'EA3C53', name: "Desire" },
  { hex: 'B9F2FF', name: "Diamond" },
  { hex: '696969', name: "Dim gray" },
  { hex: '9B7653', name: "Dirt" },
  { hex: '1E90FF', name: "Dodger blue" },
  { hex: 'D71868', name: "Dogwood rose" },
  { hex: '85BB65', name: "Dollar bill" },
  { hex: '664C28', name: "Donkey brown" },
  { hex: '967117', name: "Drab" },
  { hex: '00009C', name: "Duke blue" },
  { hex: 'E5CCC9', name: "Dust storm" },
  { hex: 'EFDFBB', name: "Dutch white" },
  { hex: 'E1A95F', name: "Earth yellow" },
  { hex: '555D50', name: "Ebony" },
  { hex: 'C2B280', name: "Ecru" },
  { hex: '1B1B1B', name: "Eerie black" },
  { hex: '614051', name: "Eggplant" },
  { hex: 'F0EAD6', name: "Eggshell" },
  { hex: '1034A6', name: "Egyptian blue" },
  { hex: '7DF9FF', name: "Electric blue" },
  { hex: 'FF003F', name: "Electric crimson" },
  { hex: '00FFFF', name: "Electric cyan" },
  { hex: '00FF00', name: "Electric green" },
  { hex: '6F00FF', name: "Electric indigo" },
  { hex: 'F4BBFF', name: "Electric lavender" },
  { hex: 'CCFF00', name: "Electric lime" },
  { hex: 'BF00FF', name: "Electric purple" },
  { hex: '3F00FF', name: "Electric ultramarine" },
  { hex: '8F00FF', name: "Electric violet" },
  { hex: 'FFFF33', name: "Electric yellow" },
  { hex: '50C878', name: "Emerald" },
  { hex: '6C3082', name: "Eminence" },
  { hex: '1B4D3E', name: "English green" },
  { hex: 'B48395', name: "English lavender" },
  { hex: 'AB4B52', name: "English red" },
  { hex: '563C5C', name: "English violet" },
  { hex: '96C8A2', name: "Eton blue" },
  { hex: '44D7A8', name: "Eucalyptus" },
  { hex: 'C19A6B', name: "Fallow" },
  { hex: '801818', name: "Falu red" },
  { hex: 'B53389', name: "Fandango" },
  { hex: 'DE5285', name: "Fandango pink" },
  { hex: 'F400A1', name: "Fashion fuchsia" },
  { hex: 'E5AA70', name: "Fawn" },
  { hex: '4D5D53', name: "Feldgrau" },
  { hex: 'FDD5B1', name: "Feldspar" },
  { hex: '4F7942', name: "Fern green" },
  { hex: 'FF2800', name: "Ferrari Red" },
  { hex: '6C541E', name: "Field drab" },
  { hex: 'B22222', name: "Firebrick" },
  { hex: 'CE2029', name: "Fire engine red" },
  { hex: 'E25822', name: "Flame" },
  { hex: 'FC8EAC', name: "Flamingo pink" },
  { hex: '6B4423', name: "Flattery" },
  { hex: 'F7E98E', name: "Flavescent" },
  { hex: 'EEDC82', name: "Flax" },
  { hex: 'A2006D', name: "Flirt" },
  { hex: 'FFFAF0', name: "Floral white" },
  { hex: 'FFBF00', name: "Fluorescent orange" },
  { hex: 'FF1493', name: "Fluorescent pink" },
  { hex: 'CCFF00', name: "Fluorescent yellow" },
  { hex: 'FF004F', name: "Folly" },
  { hex: '014421', name: "Forest green (traditional)" },
  { hex: '228B22', name: "Forest green (web)" },
  { hex: 'A67B5B', name: "French beige" },
  { hex: '856D4D', name: "French bistre" },
  { hex: '0072BB', name: "French blue" },
  { hex: 'FD3F92', name: "French fuchsia" },
  { hex: '86608E', name: "French lilac" },
  { hex: '9EFD38', name: "French lime" },
  { hex: 'D473D4', name: "French mauve" },
  { hex: 'FD6C9E', name: "French pink" },
  { hex: '811453', name: "French plum" },
  { hex: '4E1609', name: "French puce" },
  { hex: 'C72C48', name: "French raspberry" },
  { hex: 'F64A8A', name: "French rose" },
  { hex: '77B5FE', name: "French sky blue" },
  { hex: '8806CE', name: "French violet" },
  { hex: 'AC1E44', name: "French wine" },
  { hex: 'A6E7FF', name: "Fresh Air" },
  { hex: 'FF00FF', name: "Fuchsia" },
  { hex: 'C154C1', name: "Fuchsia (Crayola)" },
  { hex: 'FF77FF', name: "Fuchsia pink" },
  { hex: 'CC397B', name: "Fuchsia purple" },
  { hex: 'C74375', name: "Fuchsia rose" },
  { hex: 'E48400', name: "Fulvous" },
  { hex: 'CC6666', name: "Fuzzy Wuzzy" },
  { hex: 'E49B0F', name: "Gamboge" },
  { hex: '996600', name: "Gamboge orange (brown)" },
  { hex: '007F66', name: "Generic viridian" },
  { hex: 'F8F8FF', name: "Ghost white" },
  { hex: 'FE5A1D', name: "Giants orange" },
  { hex: 'B06500', name: "Grussrel" },
  { hex: '6082B6', name: "Glaucous" },
  { hex: 'E6E8FA', name: "Glitter" },
  { hex: '00AB66', name: "GO green" },
  { hex: 'D4AF37', name: "Gold (metallic)" },
  { hex: 'FFD700', name: "Gold (web) (Golden)" },
  { hex: '85754E', name: "Gold Fusion" },
  { hex: '996515', name: "Golden brown" },
  { hex: 'FCC200', name: "Golden poppy" },
  { hex: 'FFDF00', name: "Golden yellow" },
  { hex: 'DAA520', name: "Goldenrod" },
  { hex: 'A8E4A0', name: "Granny Smith Apple" },
  { hex: '6F2DA8', name: "Grape" },
  { hex: '808080', name: "Gray" },
  { hex: '808080', name: "Gray (HTML/CSS gray)" },
  { hex: 'BEBEBE', name: "Gray (X11 gray)" },
  { hex: '465945', name: "Gray-asparagus" },
  { hex: '8C92AC', name: "Gray-blue" },
  { hex: '00FF00', name: "Green (Color Wheel) (X11 green)" },
  { hex: '1CAC78', name: "Green (Crayola)" },
  { hex: '008000', name: "Green (HTML/CSS color)" },
  { hex: '00A877', name: "Green (Munsell)" },
  { hex: '009F6B', name: "Green (NCS)" },
  { hex: '00AD43', name: "Green (Pantone)" },
  { hex: '00A550', name: "Green (pigment)" },
  { hex: '66B032', name: "Green (RYB)" },
  { hex: '1164B4', name: "Green-blue" },
  { hex: '009966', name: "Green-cyan" },
  { hex: 'ADFF2F', name: "Green-yellow" },
  { hex: '885818', name: "Grizzly" },
  { hex: 'A99A86', name: "Grullo" },
  { hex: '00FF7F', name: "Guppie green" },
  { hex: '663854', name: "Halayà úbe" },
  { hex: '446CCF', name: "Han blue" },
  { hex: '5218FA', name: "Han purple" },
  { hex: 'E9D66B', name: "Hansa yellow" },
  { hex: '3FFF00', name: "Harlequin" },
  { hex: '46CB18', name: "Harlequin green" },
  { hex: 'C90016', name: "Harvard crimson" },
  { hex: 'DA9100', name: "Harvest gold" },
  { hex: '808000', name: "Heart Gold" },
  { hex: 'DF73FF', name: "Heliotrope" },
  { hex: 'AA98A9', name: "Heliotrope gray" },
  { hex: 'AA00BB', name: "Heliotrope magenta" },
  { hex: 'F400A1', name: "Hollywood cerise" },
  { hex: 'F0FFF0', name: "Honeydew" },
  { hex: '006DB0', name: "Honolulu blue" },
  { hex: '49796B', name: "Hooker's green" },
  { hex: 'FF1DCE', name: "Hot magenta" },
  { hex: 'FF69B4', name: "Hot pink" },
  { hex: '355E3B', name: "Hunter green" },
  { hex: '71A6D2', name: "Iceberg" },
  { hex: 'FCF75E', name: "Icterine" },
  { hex: '319177', name: "Illuminating Emerald" },
  { hex: '602F6B', name: "Imperial" },
  { hex: '002395', name: "Imperial blue" },
  { hex: '66023C', name: "Imperial purple" },
  { hex: 'ED2939', name: "Imperial red" },
  { hex: 'B2EC5D', name: "Inchworm" },
  { hex: '4C516D', name: "Independence" },
  { hex: '138808', name: "India green" },
  { hex: 'CD5C5C', name: "Indian red" },
  { hex: 'E3A857', name: "Indian yellow" },
  { hex: '6F00FF', name: "Indigo" },
  { hex: '091F92', name: "Indigo dye" },
  { hex: '4B0082', name: "Indigo (web)" },
  { hex: '002FA7', name: "International Klein Blue" },
  { hex: 'FF4F00', name: "International orange (aerospace)" },
  { hex: 'BA160C', name: "International orange (engineering)" },
  { hex: 'C0362C', name: "International orange (Golden Gate Bridge)" },
  { hex: '5A4FCF', name: "Iris" },
  { hex: 'B3446C', name: "Irresistible" },
  { hex: 'F4F0EC', name: "Isabelline" },
  { hex: '009000', name: "Islamic green" },
  { hex: 'B2FFFF', name: "Italian sky blue" },
  { hex: 'FFFFF0', name: "Ivory" },
  { hex: '00A86B', name: "Jade" },
  { hex: '9D2933', name: "Japanese carmine" },
  { hex: '264348', name: "Japanese indigo" },
  { hex: '5B3256', name: "Japanese violet" },
  { hex: 'F8DE7E', name: "Jasmine" },
  { hex: 'D73B3E', name: "Jasper" },
  { hex: 'A50B5E', name: "Jazzberry jam" },
  { hex: 'DA614E', name: "Jelly Bean" },
  { hex: '343434', name: "Jet" },
  { hex: 'F4CA16', name: "Jonquil" },
  { hex: '8AB9F1', name: "Jordy blue" },
  { hex: 'BDDA57', name: "June bud" },
  { hex: '29AB87', name: "Jungle green" },
  { hex: '4CBB17', name: "Kelly green" },
  { hex: '7C1C05', name: "Kenyan copper" },
  { hex: '3AB09E', name: "Keppel" },
  { hex: 'C3B091', name: "Jawad/Chicken Color (HTML/CSS) (Khaki)" },
  { hex: 'F0E68C', name: "Khaki (X11) (Light khaki)" },
  { hex: '882D17', name: "Kobe" },
  { hex: 'E79FC4', name: "Kobi" },
  { hex: '354230', name: "Kombu green" },
  { hex: 'E8000D', name: "KU Crimson" },
  { hex: '087830', name: "La Salle Green" },
  { hex: 'D6CADD', name: "Languid lavender" },
  { hex: '26619C', name: "Lapis lazuli" },
  { hex: 'FFFF66', name: "Laser Lemon" },
  { hex: 'A9BA9D', name: "Laurel green" },
  { hex: 'CF1020', name: "Lava" },
  { hex: 'B57EDC', name: "Lavender (floral)" },
  { hex: 'E6E6FA', name: "Lavender (web)" },
  { hex: 'CCCCFF', name: "Lavender blue" },
  { hex: 'FFF0F5', name: "Lavender blush" },
  { hex: 'C4C3D0', name: "Lavender gray" },
  { hex: '9457EB', name: "Lavender indigo" },
  { hex: 'EE82EE', name: "Lavender magenta" },
  { hex: 'E6E6FA', name: "Lavender mist" },
  { hex: 'FBAED2', name: "Lavender pink" },
  { hex: '967BB6', name: "Lavender purple" },
  { hex: 'FBA0E3', name: "Lavender rose" },
  { hex: '7CFC00', name: "Lawn green" },
  { hex: 'FFF700', name: "Lemon" },
  { hex: 'FFFACD', name: "Lemon chiffon" },
  { hex: 'CCA01D', name: "Lemon curry" },
  { hex: 'FDFF00', name: "Lemon glacier" },
  { hex: 'E3FF00', name: "Lemon lime" },
  { hex: 'F6EABE', name: "Lemon meringue" },
  { hex: 'FFF44F', name: "Lemon yellow" },
  { hex: 'BA93D8', name: "Lenurple" },
  { hex: '1A1110', name: "Licorice" },
  { hex: '545AA7', name: "Liberty" },
  { hex: 'FDD5B1', name: "Light apricot" },
  { hex: 'ADD8E6', name: "Light blue" },
  { hex: 'fe2e2e', name: "Light brilliant red" },
  { hex: 'B5651D', name: "Light brown" },
  { hex: 'E66771', name: "Light carmine pink" },
  { hex: '88ACE0', name: "Light cobalt blue" },
  { hex: 'F08080', name: "Light coral" },
  { hex: '93CCEA', name: "Light cornflower blue" },
  { hex: 'F56991', name: "Light crimson" },
  { hex: 'E0FFFF', name: "Light cyan" },
  { hex: 'FF5CCD', name: "Light deep pink" },
  { hex: 'C8AD7F', name: "Light French beige" },
  { hex: 'F984EF', name: "Light fuchsia pink" },
  { hex: 'FAFAD2', name: "Light goldenrod yellow" },
  { hex: 'D3D3D3', name: "Light gray" },
  { hex: 'CC99CC', name: "Light grayish magenta" },
  { hex: '90EE90', name: "Light green" },
  { hex: 'FFB3DE', name: "Light hot pink" },
  { hex: 'F0E68C', name: "Light khaki" },
  { hex: 'D39BCB', name: "Light medium orchid" },
  { hex: 'ADDFAD', name: "Light moss green" },
  { hex: 'E6A8D7', name: "Light orchid" },
  { hex: 'B19CD9', name: "Light pastel purple" },
  { hex: 'FFB6C1', name: "Light pink" },
  { hex: 'E97451', name: "Light red ochre" },
  { hex: 'FFA07A', name: "Light salmon" },
  { hex: 'FF9999', name: "Light salmon pink" },
  { hex: '20B2AA', name: "Light sea green" },
  { hex: '87CEFA', name: "Light sky blue" },
  { hex: '778899', name: "Light slate gray" },
  { hex: 'B0C4DE', name: "Light steel blue" },
  { hex: 'B38B6D', name: "Light taupe" },
  { hex: 'E68FAC', name: "Light Thulian pink" },
  { hex: 'FFFFE0', name: "Light yellow" },
  { hex: 'C8A2C8', name: "Lilac" },
  { hex: 'BFFF00', name: "Lime (color wheel)" },
  { hex: '00FF00', name: "Lime (web) (X11 green)" },
  { hex: '32CD32', name: "Lime green" },
  { hex: '9DC209', name: "Limerick" },
  { hex: '195905', name: "Lincoln green" },
  { hex: 'FAF0E6', name: "Linen" },
  { hex: 'C19A6B', name: "Lion" },
  { hex: 'DE6FA1', name: "Liseran Purple" },
  { hex: '6CA0DC', name: "Little boy blue" },
  { hex: '674C47', name: "Liver" },
  { hex: 'B86D29', name: "Liver (dogs)" },
  { hex: '6C2E1F', name: "Liver (organ)" },
  { hex: '987456', name: "Liver chestnut" },
  { hex: '6699CC', name: "Livid" },
  { hex: 'FFE4CD', name: "Lumber" },
  { hex: 'E62020', name: "Lust" },
  { hex: 'FF00FF', name: "Magenta" },
  { hex: 'FF55A3', name: "Magenta (Crayola)" },
  { hex: 'CA1F7B', name: "Magenta (dye)" },
  { hex: 'D0417E', name: "Magenta (Pantone)" },
  { hex: 'FF0090', name: "Magenta (process)" },
  { hex: '9F4576', name: "Magenta haze" },
  { hex: 'CC338B', name: "Magenta-pink" },
  { hex: 'AAF0D1', name: "Magic mint" },
  { hex: 'F8F4FF', name: "Magnolia" },
  { hex: 'C04000', name: "Mahogany" },
  { hex: 'FBEC5D', name: "Maize" },
  { hex: '6050DC', name: "Majorelle Blue" },
  { hex: '0BDA51', name: "Malachite" },
  { hex: '979AAA', name: "Manatee" },
  { hex: 'FF8243', name: "Mango Tango" },
  { hex: '74C365', name: "Mantis" },
  { hex: '880085', name: "Mardi Gras" },
  { hex: 'C32148', name: "Maroon (Crayola)" },
  { hex: '800000', name: "Maroon (HTML/CSS)" },
  { hex: 'B03060', name: "Maroon (X11)" },
  { hex: 'E0B0FF', name: "Mauve" },
  { hex: '915F6D', name: "Mauve taupe" },
  { hex: 'EF98AA', name: "Mauvelous" },
  { hex: '4C9141', name: "May green" },
  { hex: '73C2FB', name: "Maya blue" },
  { hex: 'E5B73B', name: "Meat brown" },
  { hex: '66DDAA', name: "Medium aquamarine" },
  { hex: '0000CD', name: "Medium blue" },
  { hex: 'E2062C', name: "Medium candy apple red" },
  { hex: 'AF4035', name: "Medium carmine" },
  { hex: 'F3E5AB', name: "Medium champagne" },
  { hex: '035096', name: "Medium electric blue" },
  { hex: '1C352D', name: "Medium jungle green" },
  { hex: 'DDA0DD', name: "Medium lavender magenta" },
  { hex: 'BA55D3', name: "Medium orchid" },
  { hex: '0067A5', name: "Medium Persian blue" },
  { hex: '9370DB', name: "Medium purple" },
  { hex: 'BB3385', name: "Medium red-violet" },
  { hex: 'AA4069', name: "Medium ruby" },
  { hex: '3CB371', name: "Medium sea green" },
  { hex: '80DAEB', name: "Medium sky blue" },
  { hex: '7B68EE', name: "Medium slate blue" },
  { hex: 'C9DC87', name: "Medium spring bud" },
  { hex: '00FA9A', name: "Medium spring green" },
  { hex: '674C47', name: "Medium taupe" },
  { hex: '48D1CC', name: "Medium turquoise" },
  { hex: '79443B', name: "Medium Tuscan red" },
  { hex: 'D9603B', name: "Medium vermilion" },
  { hex: 'C71585', name: "Medium violet-red" },
  { hex: 'F8B878', name: "Mellow apricot" },
  { hex: 'F8DE7E', name: "Mellow yellow" },
  { hex: 'FDBCB4', name: "Melon" },
  { hex: '0A7E8C', name: "Metallic Seaweed" },
  { hex: '9C7C38', name: "Metallic Sunburst" },
  { hex: 'E4007C', name: "Mexican pink" },
  { hex: '191970', name: "Midnight blue" },
  { hex: '004953', name: "Midnight green (eagle green)" },
  { hex: 'FFC40C', name: "Mikado yellow" },
  { hex: 'E3F988', name: "Mindaro" },
  { hex: '3EB489', name: "Mint" },
  { hex: 'F5FFFA', name: "Mint cream" },
  { hex: '98FF98', name: "Mint green" },
  { hex: 'FFE4E1', name: "Misty rose" },
  { hex: 'FAEBD7', name: "Moccasin" },
  { hex: '967117', name: "Mode beige" },
  { hex: '73A9C2', name: "Moonstone blue" },
  { hex: 'AE0C00', name: "Mordant red 19" },
  { hex: '8A9A5B', name: "Moss green" },
  { hex: '30BA8F', name: "Mountain Meadow" },
  { hex: '997A8D', name: "Mountbatten pink" },
  { hex: '18453B', name: "MSU Green" },
  { hex: '306030', name: "Mughal green" },
  { hex: 'C54B8C', name: "Mulberry" },
  { hex: 'FFDB58', name: "Mustard" },
  { hex: '317873', name: "Myrtle green" },
  { hex: 'F6ADC6', name: "Nadeshiko pink" },
  { hex: '2A8000', name: "Napier green" },
  { hex: 'FADA5E', name: "Naples yellow" },
  { hex: 'FFDEAD', name: "Navajo white" },
  { hex: '000080', name: "Navy" },
  { hex: '9457EB', name: "Navy purple" },
  { hex: 'FFA343', name: "Neon Carrot" },
  { hex: 'FE4164', name: "Neon fuchsia" },
  { hex: '39FF14', name: "Neon green" },
  { hex: '214FC6', name: "New Car" },
  { hex: 'D7837F', name: "New York pink" },
  { hex: 'A4DDED', name: "Non-photo blue" },
  { hex: '059033', name: "North Texas Green" },
  { hex: 'E9FFDB', name: "Nyanza" },
  { hex: '0077BE', name: "Ocean Boat Blue" },
  { hex: 'CC7722', name: "Ochre" },
  { hex: '008000', name: "Office green" },
  { hex: '43302E', name: "Old burgundy" },
  { hex: 'CFB53B', name: "Old gold" },
  { hex: '563C5C', name: "Old heliotrope" },
  { hex: 'FDF5E6', name: "Old lace" },
  { hex: '796878', name: "Old lavender" },
  { hex: '673147', name: "Old mauve" },
  { hex: '867E36', name: "Old moss green" },
  { hex: 'C08081', name: "Old rose" },
  { hex: '848482', name: "Old silver" },
  { hex: '808000', name: "Olive" },
  { hex: '6B8E23', name: "Olive Drab #3" },
  { hex: '3C341F', name: "Olive Drab #7" },
  { hex: '9AB973', name: "Olivine" },
  { hex: '353839', name: "Onyx" },
  { hex: 'B784A7', name: "Opera mauve" },
  { hex: 'FF7F00', name: "Orange (color wheel)" },
  { hex: 'FF7538', name: "Orange (Crayola)" },
  { hex: 'FF5800', name: "Orange (Pantone)" },
  { hex: 'FB9902', name: "Orange (RYB)" },
  { hex: 'FFA500', name: "Orange (web)" },
  { hex: 'FF9F00', name: "Orange peel" },
  { hex: 'FF4500', name: "Orange-red" },
  { hex: 'DA70D6', name: "Orchid" },
  { hex: 'F2BDCD', name: "Orchid pink" },
  { hex: 'FB4F14', name: "Orioles orange" },
  { hex: '654321', name: "Otter brown" },
  { hex: '414A4C', name: "Outer Space" },
  { hex: 'FF6E4A', name: "Outrageous Orange" },
  { hex: '002147', name: "Oxford Blue" },
  { hex: '990000', name: "OU Crimson Red" },
  { hex: '006600', name: "Pakistan green" },
  { hex: '273BE2', name: "Palatinate blue" },
  { hex: '682860', name: "Palatinate purple" },
  { hex: 'BCD4E6', name: "Pale aqua" },
  { hex: 'AFEEEE', name: "Pale blue" },
  { hex: '987654', name: "Pale brown" },
  { hex: 'AF4035', name: "Pale carmine" },
  { hex: '9BC4E2', name: "Pale cerulean" },
  { hex: 'DDADAF', name: "Pale chestnut" },
  { hex: 'DA8A67', name: "Pale copper" },
  { hex: 'ABCDEF', name: "Pale cornflower blue" },
  { hex: '87D3F8', name: "Pale cyan" },
  { hex: 'E6BE8A', name: "Pale gold" },
  { hex: 'EEE8AA', name: "Pale goldenrod" },
  { hex: '98FB98', name: "Pale green" },
  { hex: 'DCD0FF', name: "Pale lavender" },
  { hex: 'F984E5', name: "Pale magenta" },
  { hex: 'ff99cc', name: "Pale magenta-pink" },
  { hex: 'FADADD', name: "Pale pink" },
  { hex: 'DDA0DD', name: "Pale plum" },
  { hex: 'DB7093', name: "Pale red-violet" },
  { hex: '96DED1', name: "Pale robin egg blue" },
  { hex: 'C9C0BB', name: "Pale silver" },
  { hex: 'ECEBBD', name: "Pale spring bud" },
  { hex: 'BC987E', name: "Pale taupe" },
  { hex: 'AFEEEE', name: "Pale turquoise" },
  { hex: 'CC99FF', name: "Pale violet" },
  { hex: 'DB7093', name: "Pale violet-red" },
  { hex: '78184A', name: "Pansy purple" },
  { hex: '009B7D', name: "Paolo Veronese green" },
  { hex: 'FFEFD5', name: "Papaya whip" },
  { hex: 'E63E62', name: "Paradise pink" },
  { hex: '50C878', name: "Paris Green" },
  { hex: 'AEC6CF', name: "Pastel blue" },
  { hex: '836953', name: "Pastel brown" },
  { hex: 'CFCFC4', name: "Pastel gray" },
  { hex: '77DD77', name: "Pastel green" },
  { hex: 'F49AC2', name: "Pastel magenta" },
  { hex: 'FFB347', name: "Pastel orange" },
  { hex: 'DEA5A4', name: "Pastel pink" },
  { hex: 'B39EB5', name: "Pastel purple" },
  { hex: 'FF6961', name: "Pastel red" },
  { hex: 'CB99C9', name: "Pastel violet" },
  { hex: 'FDFD96', name: "Pastel yellow" },
  { hex: '800080', name: "Patriarch" },
  { hex: '536878', name: "Payne's grey" },
  { hex: 'FFE5B4', name: "Peach" },
  { hex: 'FFCBA4', name: "Peach" },
  { hex: 'FFCC99', name: "Peach-orange" },
  { hex: 'FFDAB9', name: "Peach puff" },
  { hex: 'FADFAD', name: "Peach-yellow" },
  { hex: 'D1E231', name: "Pear" },
  { hex: 'EAE0C8', name: "Pearl" },
  { hex: '88D8C0', name: "Pearl Aqua" },
  { hex: 'B768A2', name: "Pearly purple" },
  { hex: 'E6E200', name: "Peridot" },
  { hex: 'CCCCFF', name: "Periwinkle" },
  { hex: '1C39BB', name: "Persian blue" },
  { hex: '00A693', name: "Persian green" },
  { hex: '32127A', name: "Persian indigo" },
  { hex: 'D99058', name: "Persian orange" },
  { hex: 'F77FBE', name: "Persian pink" },
  { hex: '701C1C', name: "Persian plum" },
  { hex: 'CC3333', name: "Persian red" },
  { hex: 'FE28A2', name: "Persian rose" },
  { hex: 'EC5800', name: "Persimmon" },
  { hex: 'CD853F', name: "Peru" },
  { hex: 'DF00FF', name: "Phlox" },
  { hex: '000F89', name: "Phthalo blue" },
  { hex: '123524', name: "Phthalo green" },
  { hex: '45B1E8', name: "Picton blue" },
  { hex: 'C30B4E', name: "Pictorial carmine" },
  { hex: 'FDDDE6', name: "Piggy pink" },
  { hex: '01796F', name: "Pine green" },
  { hex: '563C5C', name: "Pineapple" },
  { hex: 'FFC0CB', name: "Pink" },
  { hex: 'D74894', name: "Pink (Pantone)" },
  { hex: 'FFDDF4', name: "Pink lace" },
  { hex: 'D8B2D1', name: "Pink lavender" },
  { hex: 'FF9966', name: "Pink-orange" },
  { hex: 'E7ACCF', name: "Pink pearl" },
  { hex: '980036', name: "Pink raspberry" },
  { hex: 'F78FA7', name: "Pink Sherbet" },
  { hex: '93C572', name: "Pistachio" },
  { hex: 'E5E4E2', name: "Platinum" },
  { hex: '8E4585', name: "Plum" },
  { hex: 'DDA0DD', name: "Plum (web)" },
  { hex: '86608E', name: "Pomp and Power" },
  { hex: 'BE4F62', name: "Popstar" },
  { hex: 'FF5A36', name: "Portland Orange" },
  { hex: 'B0E0E6', name: "Powder blue" },
  { hex: 'F58025', name: "Princeton orange" },
  { hex: '701C1C', name: "Prune" },
  { hex: '003153', name: "Prussian blue" },
  { hex: 'DF00FF', name: "Psychedelic purple" },
  { hex: 'CC8899', name: "Puce" },
  { hex: '722F37', name: "Puce red" },
  { hex: '644117', name: "Pullman Brown (UPS Brown)" },
  { hex: '3B331C', name: "Pullman Green" },
  { hex: 'FF7518', name: "Pumpkin" },
  { hex: '800080', name: "Purple (HTML)" },
  { hex: '9F00C5', name: "Purple (Munsell)" },
  { hex: 'A020F0', name: "Purple (X11)" },
  { hex: '69359C', name: "Purple Heart" },
  { hex: '9678B6', name: "Purple mountain majesty" },
  { hex: '4E5180', name: "Purple navy" },
  { hex: 'FE4EDA', name: "Purple pizzazz" },
  { hex: '50404D', name: "Purple taupe" },
  { hex: '9A4EAE', name: "Purpureus" },
  { hex: '51484F', name: "Quartz" },
  { hex: '436B95', name: "Queen blue" },
  { hex: 'E8CCD7', name: "Queen pink" },
  { hex: '8E3A59', name: "Quinacridone magenta" },
  { hex: '5D8AA8', name: "Rackley" },
  { hex: 'FF355E', name: "Radical Red" },
  { hex: 'FBAB60', name: "Rajah" },
  { hex: 'E30B5D', name: "Raspberry" },
  { hex: '915F6D', name: "Raspberry glace" },
  { hex: 'E25098', name: "Raspberry pink" },
  { hex: 'B3446C', name: "Raspberry rose" },
  { hex: '826644', name: "Raw umber" },
  { hex: 'FF33CC', name: "Razzle dazzle rose" },
  { hex: 'E3256B', name: "Razzmatazz" },
  { hex: '8D4E85', name: "Razzmic Berry" },
  { hex: '663399', name: "Rebecca Purple" },
  { hex: 'FF0000', name: "Red" },
  { hex: 'EE204D', name: "Red (Crayola)" },
  { hex: 'F2003C', name: "Red (Munsell)" },
  { hex: 'C40233', name: "Red (NCS)" },
  { hex: 'ED2939', name: "Red (Pantone)" },
  { hex: 'ED1C24', name: "Red (pigment)" },
  { hex: 'FE2712', name: "Red (RYB)" },
  { hex: 'A52A2A', name: "Red-brown" },
  { hex: '860111', name: "Red devil" },
  { hex: 'FF5349', name: "Red-orange" },
  { hex: 'E40078', name: "Red-purple" },
  { hex: 'C71585', name: "Red-violet" },
  { hex: 'A45A52', name: "Redwood" },
  { hex: '522D80', name: "Regalia" },
  { hex: '000000', name: "Registration black" },
  { hex: '002387', name: "Resolution blue" },
  { hex: '777696', name: "Rhythm" },
  { hex: '000000', name: "Rich black (typical)" },
  { hex: '010B13', name: "Rich black (FOGRA29)" },
  { hex: '010203', name: "Rich black (FOGRA39)" },
  { hex: 'F1A7FE', name: "Rich brilliant lavender" },
  { hex: 'D70040', name: "Rich carmine" },
  { hex: '0892D0', name: "Rich electric blue" },
  { hex: 'A76BCF', name: "Rich lavender" },
  { hex: 'B666D2', name: "Rich lilac" },
  { hex: 'B03060', name: "Rich maroon" },
  { hex: '444C38', name: "Rifle green" },
  { hex: '704241', name: "Roast coffee" },
  { hex: '00CCCC', name: "Robin egg blue" },
  { hex: '8A7F80', name: "Rocket metallic" },
  { hex: '838996', name: "Roman silver" },
  { hex: 'FF007F', name: "Rose" },
  { hex: 'F9429E', name: "Rose bonbon" },
  { hex: '674846', name: "Rose ebony" },
  { hex: 'B76E79', name: "Rose gold" },
  { hex: 'E32636', name: "Rose madder" },
  { hex: 'FF66CC', name: "Rose pink" },
  { hex: 'AA98A9', name: "Rose quartz" },
  { hex: 'C21E56', name: "Rose red" },
  { hex: '905D5D', name: "Rose taupe" },
  { hex: 'AB4E52', name: "Rose vale" },
  { hex: '65000B', name: "Rosewood" },
  { hex: 'D40000', name: "Rosso corsa" },
  { hex: 'BC8F8F', name: "Rosy brown" },
  { hex: '0038A8', name: "Royal azure" },
  { hex: '002366', name: "Royal blue" },
  { hex: '4169E1', name: "Royal blue" },
  { hex: 'CA2C92', name: "Royal fuchsia" },
  { hex: '7851A9', name: "Royal purple" },
  { hex: 'FADA5E', name: "Royal yellow" },
  { hex: 'CE4676', name: "Ruber" },
  { hex: 'D10056', name: "Rubine red" },
  { hex: 'E0115F', name: "Ruby" },
  { hex: '9B111E', name: "Ruby red" },
  { hex: 'FF0028', name: "Ruddy" },
  { hex: 'BB6528', name: "Ruddy brown" },
  { hex: 'E18E96', name: "Ruddy pink" },
  { hex: 'A81C07', name: "Rufous" },
  { hex: '80461B', name: "Russet" },
  { hex: '679267', name: "Russian green" },
  { hex: '32174D', name: "Russian violet" },
  { hex: 'B7410E', name: "Rust" },
  { hex: 'DA2C43', name: "Rusty red" },
  { hex: '00563F', name: "Sacramento State green" },
  { hex: '8B4513', name: "Saddle brown" },
  { hex: 'FF7800', name: "Safety orange" },
  { hex: 'FF6700', name: "Safety orange (blaze orange)" },
  { hex: 'EED202', name: "Safety yellow" },
  { hex: 'F4C430', name: "Saffron" },
  { hex: 'BCB88A', name: "Sage" },
  { hex: '23297A', name: "St. Patrick's blue" },
  { hex: 'FA8072', name: "Salmon" },
  { hex: 'FF91A4', name: "Salmon pink" },
  { hex: 'C2B280', name: "Sand" },
  { hex: '967117', name: "Sand dune" },
  { hex: 'ECD540', name: "Sandstorm" },
  { hex: 'F4A460', name: "Sandy brown" },
  { hex: '967117', name: "Sandy taupe" },
  { hex: '92000A', name: "Sangria" },
  { hex: '507D2A', name: "Sap green" },
  { hex: '0F52BA', name: "Sapphire" },
  { hex: '0067A5', name: "Sapphire blue" },
  { hex: 'CBA135', name: "Satin sheen gold" },
  { hex: 'FF2400', name: "Scarlet" },
  { hex: 'FD0E35', name: "Scarlet" },
  { hex: 'FF91AF', name: "Schauss pink" },
  { hex: 'FFD800', name: "School bus yellow" },
  { hex: '76FF7A', name: "Screamin' Green" },
  { hex: '006994', name: "Sea blue" },
  { hex: '2E8B57', name: "Sea green" },
  { hex: '321414', name: "Seal brown" },
  { hex: 'FFF5EE', name: "Seashell" },
  { hex: 'FFBA00', name: "Selective yellow" },
  { hex: '704214', name: "Sepia" },
  { hex: '8A795D', name: "Shadow" },
  { hex: '778BA5', name: "Shadow blue" },
  { hex: 'FFCFF1', name: "Shampoo" },
  { hex: '009E60', name: "Shamrock green" },
  { hex: '8FD400', name: "Sheen Green" },
  { hex: 'D98695', name: "Shimmering Blush" },
  { hex: 'FC0FC0', name: "Shocking pink" },
  { hex: 'FF6FFF', name: "Shocking pink (Crayola)" },
  { hex: '882D17', name: "Sienna" },
  { hex: 'C0C0C0', name: "Silver" },
  { hex: 'ACACAC', name: "Silver chalice" },
  { hex: '5D89BA', name: "Silver Lake blue" },
  { hex: 'C4AEAD', name: "Silver pink" },
  { hex: 'BFC1C2', name: "Silver sand" },
  { hex: 'CB410B', name: "Sinopia" },
  { hex: '007474', name: "Skobeloff" },
  { hex: '87CEEB', name: "Sky blue" },
  { hex: 'CF71AF', name: "Sky magenta" },
  { hex: '6A5ACD', name: "Slate blue" },
  { hex: '708090', name: "Slate gray" },
  { hex: '003399', name: "Smalt (Dark powder blue)" },
  { hex: 'C84186', name: "Smitten" },
  { hex: '738276', name: "Smoke" },
  { hex: '100C08', name: "Smoky black" },
  { hex: '933D41', name: "Smoky Topaz" },
  { hex: 'FFFAFA', name: "Snow" },
  { hex: 'CEC8EF', name: "Soap" },
  { hex: '893843', name: "Solid pink" },
  { hex: '757575', name: "Sonic silver" },
  { hex: '9E1316', name: "Spartan Crimson" },
  { hex: '1D2951', name: "Space cadet" },
  { hex: '807532', name: "Spanish bistre" },
  { hex: '0070B8', name: "Spanish blue" },
  { hex: 'D10047', name: "Spanish carmine" },
  { hex: 'E51A4C', name: "Spanish crimson" },
  { hex: '989898', name: "Spanish gray" },
  { hex: '009150', name: "Spanish green" },
  { hex: 'E86100', name: "Spanish orange" },
  { hex: 'F7BFBE', name: "Spanish pink" },
  { hex: 'E60026', name: "Spanish red" },
  { hex: '00FFFF', name: "Spanish sky blue" },
  { hex: '4C2882', name: "Spanish violet" },
  { hex: '007F5C', name: "Spanish viridian" },
  { hex: '8b5f4d', name: "Spicy mix" },
  { hex: '0FC0FC', name: "Spiro Disco Ball" },
  { hex: 'A7FC00', name: "Spring bud" },
  { hex: '00FF7F', name: "Spring green" },
  { hex: '007BB8', name: "Star command blue" },
  { hex: '4682B4', name: "Steel blue" },
  { hex: 'CC33CC', name: "Steel pink" },
  { hex: 'FADA5E', name: "Stil de grain yellow" },
  { hex: '990000', name: "Stizza" },
  { hex: '4F666A', name: "Stormcloud" },
  { hex: 'E4D96F', name: "Straw" },
  { hex: 'FC5A8D', name: "Strawberry" },
  { hex: 'FFCC33', name: "Sunglow" },
  { hex: 'E3AB57', name: "Sunray" },
  { hex: 'FAD6A5', name: "Sunset" },
  { hex: 'FD5E53', name: "Sunset orange" },
  { hex: 'CF6BA9', name: "Super pink" },
  { hex: 'D2B48C', name: "Tan" },
  { hex: 'F94D00', name: "Tangelo" },
  { hex: 'F28500', name: "Tangerine" },
  { hex: 'FFCC00', name: "Tangerine yellow" },
  { hex: 'E4717A', name: "Tango pink" },
  { hex: '483C32', name: "Taupe" },
  { hex: '8B8589', name: "Taupe gray" },
  { hex: 'D0F0C0', name: "Tea green" },
  { hex: 'F88379', name: "Tea rose" },
  { hex: 'F4C2C2', name: "Tea rose" },
  { hex: '008080', name: "Teal" },
  { hex: '367588', name: "Teal blue" },
  { hex: '99E6B3', name: "Teal deer" },
  { hex: '00827F', name: "Teal green" },
  { hex: 'CF3476', name: "Telemagenta" },
  { hex: 'CD5700', name: "Tenné" },
  { hex: 'E2725B', name: "Terra cotta" },
  { hex: 'D8BFD8', name: "Thistle" },
  { hex: 'DE6FA1', name: "Thulian pink" },
  { hex: 'FC89AC', name: "Tickle Me Pink" },
  { hex: '0ABAB5', name: "Tiffany Blue" },
  { hex: 'E08D3C', name: "Tiger's eye" },
  { hex: 'DBD7D2', name: "Timberwolf" },
  { hex: 'EEE600', name: "Titanium yellow" },
  { hex: 'FF6347', name: "Tomato" },
  { hex: '746CC0', name: "Toolbox" },
  { hex: 'FFC87C', name: "Topaz" },
  { hex: 'FD0E35', name: "Tractor red" },
  { hex: '808080', name: "Trolley Grey" },
  { hex: '00755E', name: "Tropical rain forest" },
  { hex: '0073CF', name: "True Blue" },
  { hex: '417DC1', name: "Tufts Blue" },
  { hex: 'FF878D', name: "Tulip" },
  { hex: 'DEAA88', name: "Tumbleweed" },
  { hex: 'B57281', name: "Turkish rose" },
  { hex: '40E0D0', name: "Turquoise" },
  { hex: '00FFEF', name: "Turquoise blue" },
  { hex: 'A0D6B4', name: "Turquoise green" },
  { hex: 'FAD6A5', name: "Tuscan" },
  { hex: '6F4E37', name: "Tuscan brown" },
  { hex: '7C4848', name: "Tuscan red" },
  { hex: 'A67B5B', name: "Tuscan tan" },
  { hex: 'C09999', name: "Tuscany" },
  { hex: '8A496B', name: "Twilight lavender" },
  { hex: '66023C', name: "Tyrian purple" },
  { hex: '0033AA', name: "UA blue" },
  { hex: 'D9004C', name: "UA red" },
  { hex: '8878C3', name: "Ube" },
  { hex: '536895', name: "UCLA Blue" },
  { hex: 'FFB300', name: "UCLA Gold" },
  { hex: '3CD070', name: "UFO Green" },
  { hex: '120A8F', name: "Ultramarine" },
  { hex: '4166F5', name: "Ultramarine blue" },
  { hex: 'FF6FFF', name: "Ultra pink" },
  { hex: 'FC6C85', name: "Ultra red" },
  { hex: '635147', name: "Umber" },
  { hex: 'FFDDCA', name: "Unbleached silk" },
  { hex: '5B92E5', name: "United Nations blue" },
  { hex: 'B78727', name: "University of California Gold" },
  { hex: 'FFFF66', name: "Unmellow yellow" },
  { hex: '014421', name: "UP Forest green" },
  { hex: '7B1113', name: "UP Maroon" },
  { hex: 'AE2029', name: "Upsdell red" },
  { hex: 'E1AD21', name: "Urobilin" },
  { hex: '004F98', name: "USAFA blue" },
  { hex: '990000', name: "USC Cardinal" },
  { hex: 'FFCC00', name: "USC Gold" },
  { hex: 'F77F00', name: "University of Tennessee Orange" },
  { hex: 'D3003F', name: "Utah Crimson" },
  { hex: 'F3E5AB', name: "Vanilla" },
  { hex: 'F38FA9', name: "Vanilla ice" },
  { hex: 'C5B358', name: "Vegas gold" },
  { hex: 'C80815', name: "Venetian red" },
  { hex: '43B3AE', name: "Verdigris" },
  { hex: 'E34234', name: "Vermilion" },
  { hex: 'D9381E', name: "Vermilion" },
  { hex: 'A020F0', name: "Veronica" },
  { hex: '74BBFB', name: "Very light azure" },
  { hex: '6666FF', name: "Very light blue" },
  { hex: '64E986', name: "Very light malachite green" },
  { hex: 'FFB077', name: "Very light tangelo" },
  { hex: 'FFDFBF', name: "Very pale orange" },
  { hex: 'FFFFBF', name: "Very pale yellow" },
  { hex: '8F00FF', name: "Violet" },
  { hex: '7F00FF', name: "Violet (color wheel)" },
  { hex: '8601AF', name: "Violet (RYB)" },
  { hex: 'EE82EE', name: "Violet (web)" },
  { hex: '324AB2', name: "Violet-blue" },
  { hex: 'F75394', name: "Violet-red" },
  { hex: '40826D', name: "Viridian" },
  { hex: '009698', name: "Viridian green" },
  { hex: '7C9ED9', name: "Vista blue" },
  { hex: 'cc9900', name: "Vivid amber" },
  { hex: '922724', name: "Vivid auburn" },
  { hex: '9F1D35', name: "Vivid burgundy" },
  { hex: 'DA1D81', name: "Vivid cerise" },
  { hex: '00aaee', name: "Vivid cerulean" },
  { hex: 'CC0033', name: "Vivid crimson" },
  { hex: 'FF9900', name: "Vivid gamboge" },
  { hex: 'a6d608', name: "Vivid lime green" },
  { hex: '00cc33', name: "Vivid malachite" },
  { hex: 'B80CE3', name: "Vivid mulberry" },
  { hex: 'FF5F00', name: "Vivid orange" },
  { hex: 'FFA000', name: "Vivid orange peel" },
  { hex: 'CC00FF', name: "Vivid orchid" },
  { hex: 'FF006C', name: "Vivid raspberry" },
  { hex: 'F70D1A', name: "Vivid red" },
  { hex: 'DF6124', name: "Vivid red-tangelo" },
  { hex: '00CCFF', name: "Vivid sky blue" },
  { hex: 'F07427', name: "Vivid tangelo" },
  { hex: 'FFA089', name: "Vivid tangerine" },
  { hex: 'e56024', name: "Vivid vermilion" },
  { hex: '9F00FF', name: "Vivid violet" },
  { hex: 'FFE302', name: "Vivid yellow" },
  { hex: '000000', name: "Warm black" },
  { hex: 'A4F4F9', name: "Waterspout" },
  { hex: '645452', name: "Wenge" },
  { hex: 'F5DEB3', name: "Wheat" },
  { hex: 'FFFFFF', name: "White" },
  { hex: 'F5F5F5', name: "White smoke" },
  { hex: 'A2ADD0', name: "Wild blue yonder" },
  { hex: 'D470A2', name: "Wild orchid" },
  { hex: 'FF43A4', name: "Wild Strawberry" },
  { hex: 'FC6C85', name: "Wild watermelon" },
  { hex: 'FD5800', name: "Willpower orange" },
  { hex: 'A75502', name: "Windsor tan" },
  { hex: '722F37', name: "Wine" },
  { hex: '673147', name: "Wine dregs" },
  { hex: 'C9A0DC', name: "Wisteria" },
  { hex: 'C19A6B', name: "Wood brown" },
  { hex: '738678', name: "Xanadu" },
  { hex: '0F4D92', name: "Yale Blue" },
  { hex: '1C2841', name: "Yankees blue" },
  { hex: 'FFFF00', name: "Yellow" },
  { hex: 'FCE883', name: "Yellow (Crayola)" },
  { hex: 'EFCC00', name: "Yellow (Munsell)" },
  { hex: 'FFD300', name: "Yellow (NCS)" },
  { hex: 'FEDF00', name: "Yellow (Pantone)" },
  { hex: 'FFEF00', name: "Yellow (process)" },
  { hex: 'FEFE33', name: "Yellow (RYB)" },
  { hex: '9ACD32', name: "Yellow-green" },
  { hex: 'FFAE42', name: "Yellow Orange" },
  { hex: 'FFF000', name: "Yellow rose" },
  { hex: '0014A8', name: "Zaffre" },
  { hex: '2C1608', name: "Zinnwaldite brown" },
  { hex: '39A78E', name: "Zomp" }
]

$.widget "custom.colorTags",
  _create: ()->
    formatColorItem = (item)->
      "<div style='background-color: ##{item.id}; width: 20px; height: 1em; display: inline-block; vertical-align: bottom;'></div> #{item.text}"
    isColorHex = (text)->
      /^[0-9A-F]{6}$/i.test(text)

    @element.select2({
      tags: $.map(colorNames, (color)->
        { id: color.hex, text: color.name}
      )
      formatSelection: formatColorItem
      formatResult: formatColorItem
    }).on('select2-selecting', (e)->
      e.preventDefault() unless isColorHex(e.val)
    ).on('change');

    @element.select2('readonly', true) if @options.readonly
