# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

development:
  mailer_address: ''
  mailer_password: ''
  S3_BUCKET_NAME: 'icrowd-development'
  AWS_ACCESS_KEY: AKIAJH6V52XNVZ4Y7X6Q
  AWS_SECRET_ACCESS_KEY: 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
  MANDRILL_EMAIL: 'hello@interiorcrowd.com'
  MANDRILL_API_TOKEN: 'IqRBhcv59Pu64Z1UVXg7pg'
  INFO_EMAIL: 'romans@softwareplanet.uk.com'
  BETA_PASSWORD: 'beta'
  APP_HOST: 'localhost:3000'
  MARKS_DIGEST_MINUTES_INTERVAL: '1'
  COMMENT_BOARD_DIGEST_MINUTES_INTERVAL: '1'
  MIXPANEL_TOKEN: 44f85b93d0a057277bc70151571c80a0
  APP_URL: 'http://localhost:3000'
  GOOGLE_ANALYTICS_PROPERTY_ID: '0'
  STRIPE_API_KEY: sk_test_iKogRUxGem219WsRGVGPhBw4
  STRIPE_PUBLISHABLE_API_KEY: pk_test_rKCduto40j9ipbJSDaAR3waH
  FACEBOOK_APP_ID: '379444088920818'
  FACEBOOK_APP_SECRET: '7084b1a31a9c4e42189ab8abbc9102bc'
  NEWRELIC_KEY: '2696663eb045f2a82f31ad853b7c392fc1ae9cbf'
  MAILCHIMP_API_KEY: 'eb621bf07bea7c8316bfe3477a48b981-us12'
  MAILCHIMP_LIST_ID: '854c60de30'
  SHOW_PACKAGE_TYPE_DESC: 'false'
  AUTOMATIC_PAYMENT: 'true'
  ROLLBAR_JS_ACCESS_TOKEN: '4d6c88dd31bc4667a66ae7b22f259873' # pustomytnyk@gmail.com account
  ROLLBAR_ACCESS_TOKEN: 'befcb19850e14ee9b77146367b341c16'

test:
  APP_HOST: 'localhost:3000'
  FACEBOOK_APP_ID: 'dummy'
  FACEBOOK_APP_SECRET: 'dummy'
  INFO_EMAIL: 'romans@softwareplanet.uk.com'
  INBOUND_MAIL_DOMAIN: 'inbound.test.com'
