common: &defaults
  mailer:
    address: <%= ENV['MAILER_ADDRESS'] %>
    password: <%= ENV['MAILER_PASSWORD'] %>
  aws:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
    access_key: <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  mandrill:
    email: <%= ENV['MANDRILL_EMAIL'] %>
    api_token: <%= ENV['MANDRILL_API_TOKEN'] %>
  info_email: <%= ENV['INFO_EMAIL'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  rollbar_js_access_token: <%= ENV['ROLLBAR_JS_ACCESS_TOKEN'] %>
  root_folder: <%= Rails.root %>
  app_host: <%= ENV['APP_HOST'] %>
  app_url: <%= ENV['APP_URL'] %>
  marks_digest_minutes_interval:  <%= ENV['MARKS_DIGEST_MINUTES_INTERVAL'] %>
  comment_board_digest_minutes_interval: <%= ENV['COMMENT_BOARD_DIGEST_MINUTES_INTERVAL'] %>
  mixpanel_token: <%= ENV['MIXPANEL_TOKEN'] %>
  google_analytics_property_id: <%= ENV['GOOGLE_ANALYTICS_PROPERTY_ID'] %>
  stripe_api_key: <%= ENV['STRIPE_API_KEY'] %>
  stripe:
    api_key: <%= ENV['STRIPE_API_KEY'] %>
    publishable_api_key: <%= ENV['STRIPE_PUBLISHABLE_API_KEY'] %>
  external_urls:
    blog_url: http://blog.interiorcrowd.com
    blog_get_ideas: http://blog.interiorcrowd.com/category/get-ideas
    blog_client_stories: http://blog.interiorcrowd.com/category/client-stories
    blog_design_styles: http://blog.interiorcrowd.com/category/get-ideas/design-styles
    blog_about_us: http://blog.interiorcrowd.com/category/about-us
    ic_twitter: https://twitter.com/InteriorCrowd
    ic_facebook: https://www.facebook.com/interiorcrowd
    ic_instagram: https://instagram.com/interiorcrowd
    ic_pinterest: https://www.pinterest.com/interiorcrowd
    stripe_js: https://js.stripe.com/v2/
    privacy_policy_tw_support: https://support.twitter.com/articles/20170405
    privacy_policy_google_gaoptout: https://tools.google.com/dlpage/gaoptout
    privacy_policy_google_settings_ads: http://www.google.com/settings/ads
    privacy_policy_google_analytics_terms: http://www.google.com/analytics/terms/us.html
    privacy_policy_aboutads: http://www.aboutads.info/choices

development:

test:

staging:

production:
  beta_notification_emails: <%=  ENV['BETA_NOTIFICATION_EMAILS'] && ENV['BETA_NOTIFICATION_EMAILS'].split(',') %>
