common: &defaults
  mailer:
    address: <%= ENV['MAILER_ADDRESS'] %>
    password: <%= ENV['MAILER_PASSWORD'] %>
  aws:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
    access_key: <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  mandrill:
    email: <%= ENV['MANDRILL_EMAIL'] %>
    api_token: <%= ENV['MANDRILL_API_TOKEN'] %>
  info_email: <%= ENV['INFO_EMAIL'] %>
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  rollbar_js_access_token: <%= ENV['ROLLBAR_JS_ACCESS_TOKEN'] %>
  root_folder: <%= Rails.root %>
  app_host: <%= ENV['APP_HOST'] %>
  app_url: <%= ENV['APP_URL'] %>
  marks_digest_minutes_interval:  <%= ENV['MARKS_DIGEST_MINUTES_INTERVAL'] %>
  comment_board_digest_minutes_interval: <%= ENV['COMMENT_BOARD_DIGEST_MINUTES_INTERVAL'] %>
  mixpanel_token: <%= ENV['MIXPANEL_TOKEN'] %>
  google_analytics_property_id: <%= ENV['GOOGLE_ANALYTICS_PROPERTY_ID'] %>
  stripe_api_key: <%= ENV['STRIPE_API_KEY'] %>
  stripe:
    api_key: <%= ENV['STRIPE_API_KEY'] %>
    publishable_api_key: <%= ENV['STRIPE_PUBLISHABLE_API_KEY'] %>
  external_urls:
    blog:
      url: http://blog.interiorcrowd.com
      get_ideas: http://blog.interiorcrowd.com/category/get-ideas
      client_stories: http://blog.interiorcrowd.com/category/client-stories
      design_styles: http://blog.interiorcrowd.com/category/get-ideas/design-styles
      about_us: http://blog.interiorcrowd.com/about-us
      justines_story: http://blog.interiorcrowd.com/justines-story
      designer_submission: http://blog.interiorcrowd.com/designer-acquisition
    social:
      twitter: https://twitter.com/InteriorCrowd
      facebook: https://www.facebook.com/interiorcrowd
      instagram: https://instagram.com/interiorcrowd
      pinterest: https://www.pinterest.com/interiorcrowd
    stripe_js: https://js.stripe.com/v2/
    privacy_policy:
      twitter_tailored_ads: https://support.twitter.com/articles/20170405
      google_opt_out_addon: https://tools.google.com/dlpage/gaoptout
      google_ads_settings: http://www.google.com/settings/ads
      google_analytics_terms: http://www.google.com/analytics/terms/us.html
      about_ads_choices: http://www.aboutads.info/choices
  designer_level_pictures:
    novice: '/assets/design_levels/novice.jpg'
    enthusiast: '/assets/design_levels/enthusiast.jpg'
    savvy: '/assets/design_levels/savvy.jpg'
  ably:
    api_key: CRyt2w.7HSMCw:PI3GpWgTHK8KBZ67
    feedback_channel: product_item_feedback
    script_url: http://cdn.ably.io/lib/ably.min.js

development:

test:

staging:

production:
  beta_notification_emails: <%=  ENV['BETA_NOTIFICATION_EMAILS'] && ENV['BETA_NOTIFICATION_EMAILS'].split(',') %>
