common: &defaults
  mailer:
    address: <%= ENV['MAILER_ADDRESS'] %>
    password: <%= ENV['MAILER_PASSWORD'] %>
  aws:
    bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
    access_key: <%= ENV['AWS_ACCESS_KEY'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  mandrill:
    email: <%= ENV['MANDRILL_EMAIL'] %>
    api_token: <%= ENV['MANDRILL_API_TOKEN'] %>
    webhook_key: <%= ENV['MANDRILL_WEBHOOK_KEY'] %>
  mailchimp:
    api_key: <%= ENV['MAILCHIMP_API_KEY'] %>
    list_id: <%= ENV['MAILCHIMP_LIST_ID'] %>
  pinterest:
    landing_tracking_id: 'hRXcYaFTu2E'
    checkout_tracking_id: 'OqVkf6X2IST'
    intake_form_tracking_id: 'SquY36PB2Bn'
  hotjar_id: <%= ENV['HOTJAR_ID'] %>
  pictures_email: pictures@interiorcrowd.com
  info_email: <%= ENV['INFO_EMAIL'] %>
  contact_phone: '+1 (256) 515-4863'
  winning_designers_notification_email: 'ruth@interiorcrowd.com'
  rollbar_access_token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
  rollbar_js_access_token: <%= ENV['ROLLBAR_JS_ACCESS_TOKEN'] %>
  root_folder: <%= Rails.root %>
  app_host: <%= ENV['APP_HOST'] %>
  app_domain: <%= ENV['APP_HOST'] %>
  app_url: <%= ENV['APP_URL'] %>
  marks_digest_minutes_interval:  <%= ENV['MARKS_DIGEST_MINUTES_INTERVAL'] %>
  comment_board_digest_minutes_interval: <%= ENV['COMMENT_BOARD_DIGEST_MINUTES_INTERVAL'] %>
  mixpanel_token: <%= ENV['MIXPANEL_TOKEN'] %>
  google_analytics_property_id: <%= ENV['GOOGLE_ANALYTICS_PROPERTY_ID'] %>
  stripe_api_key: <%= ENV['STRIPE_API_KEY'] %>
  stripe:
    api_key: <%= ENV['STRIPE_API_KEY'] %>
    publishable_api_key: <%= ENV['STRIPE_PUBLISHABLE_API_KEY'] %>
  external_urls:
    blog:
      blog_url: http://blog.interiorcrowd.com
      designers_blog_url: http://designers.interiorcrowd.com
      get_ideas: http://blog.interiorcrowd.com/category/get-ideas
      client_stories: http://blog.interiorcrowd.com/category/client-stories
      design_styles: http://blog.interiorcrowd.com/category/get-ideas/design-styles
      about_us: http://blog.interiorcrowd.com/about-us
      justines_story: http://blog.interiorcrowd.com/justines-story
    social:
      twitter: https://twitter.com/InteriorCrowd
      facebook: https://www.facebook.com/interiorcrowd
      instagram: https://instagram.com/interiorcrowd
      pinterest: https://www.pinterest.com/interiorcrowd
    stripe_js: https://js.stripe.com/v2/
    privacy_policy:
      twitter_tailored_ads: https://support.twitter.com/articles/20170405
      google_opt_out_addon: https://tools.google.com/dlpage/gaoptout
      google_ads_settings: http://www.google.com/settings/ads
      google_analytics_terms: http://www.google.com/analytics/terms/us.html
      about_ads_choices: http://www.aboutads.info/choices
    font_awesome_css: https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css
    linkedin_accounts:
      - https://www.linkedin.com/in/heathernatsch
      - https://www.linkedin.com/in/helene-de-baubigny-0a57055a
      - https://www.linkedin.com/profile/view?id=AAkAAAAe3t4BXYLIWQPLh7ngKQ-lQdyQxGfW8n0&authType=NAME_SEARCH&authToken=yikt&locale=en_US&trk=tyah&trkInfo=clickedVertical%3Amynetwork%2CclickedEntityId%3A2023134%2CauthType%3ANAME_SEARCH%2Cidx%3A1-1-1%2CtarId%3A1448391047406%2Ctas%3Aerik%20ne
      - https://www.linkedin.com/in/ruthleroux5000/
      - https://www.linkedin.com/in/ana-maria-lopez-3470146
      - https://www.linkedin.com/in/claireandreas
      - https://www.linkedin.com/in/jolene-lindner-3abaa827
      - https://www.linkedin.com/in/nat-suriyapee-769954a3
      - https://www.linkedin.com/in/lia-aprile-18017410a
  designer_note_profile_image: '/assets/profile-img.png'
  designer_level_pictures:
    novice: '/assets/design_levels/novice.jpg'
    enthusiast: '/assets/design_levels/enthusiast.jpg'
    savvy: '/assets/design_levels/savvy.jpg'
  ably:
    api_key: CRyt2w.7HSMCw:PI3GpWgTHK8KBZ67
    script_url: http://cdn.ably.io/lib/ably.min.js
    product_item_feedback: product_item_feedback_for_contest_request_with_id_
  facebook:
    app_id: '<%= ENV['FACEBOOK_APP_ID'] %>'
    secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
    pixel_id: <%= ENV['FACEBOOK_PIXEL_ID'] %>
  show_beta_functionality: <%= !Rails.env.production? %>
  log_requests_to_blog: <%= Rails.env.development? %>
  automatic_payment: <%= ENV['AUTOMATIC_PAYMENT'] == 'true' %>
  designer_training_videos:
    initial_phase:
      url: 'http://www.screencast.com/t/P1CGZXKu4'
      player_url: 'http://content.screencast.com/users/interiorcrowd5000/folders/Jing/media/6e97bb27-c6aa-48a5-98d2-90ef9b362c54/'
      version: '00000005'
      width: 1440
      height: 807
    product_list_phase:
      url: 'http://www.screencast.com/t/ZW5KUEJ9'
      player_url: 'http://content.screencast.com/users/interiorcrowd5000/folders/Jing/media/884d6483-17f1-474c-a62e-e3f22a52edcd/'
      version: '00000006'
      width: 1440
      height: 807
    final_design_phase:
      url: 'http://www.screencast.com/t/00OHzHGcm'
      player_url: 'http://content.screencast.com/users/interiorcrowd5000/folders/Jing/media/ff153cb6-cb14-4b59-8fbc-fd096353e5e8/'
      version: '00000010'
      width: 1440
      height: 900
  viglink_key: '<%= ENV['VIGLINK_KEY'] %>'
  designer_submission_iframe_source: 'https://docs.google.com/forms/d/1_vJzmTLzAc7xn9D5Z-RoQW278wF6WSim-VW37RNUzqM/viewform?embedded=true'
  max_session_duration_secs: <%= 2.weeks.to_i %>
  show_portfolio_reviews: <%= false %>
  send_emails: <%= !Rails.env.development? %>
  handle_errors: <%= !Rails.env.development? %>
  enable_google_conversion_script: <%= Rails.env.production? || Rails.env.staging? %>
  blog:
    api:
      path: <%= ENV['BLOG_API_PATH'] %>
      username: <%= ENV['BLOG_API_USERNAME'] %>
      password: <%= ENV['BLOG_API_PASSWORD'] %>

development:
  <<: *defaults
  hotjar_id:
  development_panel: true

test:
  <<: *defaults
  mailchimp:
    api_key: '1234-us1'
    list_id: '123'

staging:
  <<: *defaults

production:
  <<: *defaults
  beta_notification_emails: <%=  ENV['BETA_NOTIFICATION_EMAILS'] && ENV['BETA_NOTIFICATION_EMAILS'].split(',') %>
